version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_net

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mongo_net

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mongo_net

networks:
  mongo_net:

volumes:
  mongodb_data:
    driver: local
