version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_net

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mongo_net

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - "8001:8001"
    networks:
      - mongo_net

networks:
  mongo_net:

volumes:
  mongodb_data:
    driver: local
